### PR TITLE
Raj19022000 patch 1

### PR DESCRIPTION
**Pull request by RajGhugare19**

### CODE REVIEW

**Comment by take2rohit** [comment]
@Raj19022000 I have resolved the conflict. I will merge it once verified. 
Just for your knowledge, you don't need to type the link. You can simply give the folder path. See the latest master branch `README.md` for example or see dea5759

**Comment by akshaykulkarni07** [comment]
@Raj19022000 Please change the folder name to `mathematics` instead of `Mathematics` for consistency.

**Comment by Raj19022000** [comment]
@akshaykvnit In my branch it is Mathematics

**Comment by RajGhugare19** [comment]
@akshaykvnit Its done

**Comment by akshaykulkarni07** [comment]
You forgot to change the name in the link in the main README. Also, see how @take2rohit had linked the folders with just the name of the folder and not the entire link.

**Comment by take2rohit** [comment]
@Raj19022000 i corrected the hyperlinks in main readme. You again reverted back.
Please use the compact form of hyper linking
See this readme for example
https://github.com/IvLabs/ResearchPaperNotes/blob/master/README.md

**Comment by RajGhugare19** [comment]
@akshaykvnit is it alright now?

**Comment by akshaykulkarni07** [comment]
There are minor changes, but I'll make those myself instead of stretching this more. I'm merging.

**Pull request merged**
