### PR TITLE
Resources

### PR DESCRIPTION
**Pull request by Aniket-Gujarathi**
I have added some resources for state-estimation and localization. Also, I have added certain things in motion planning and controls sections. Kindly review them.

### CODE REVIEW

**Comment by akshaykulkarni07** [comment]
I think it's good as far as formatting is concerned. If you can make the other things (added by Unmesh) also consistent, that would be very good. @Aniket-Gujarathi

**Comment by take2rohit** [comment]
@Aniket-Gujarathi the name of folder isn't consistent `State Estimation and Localization, SLAM` should be renamed to something like `state- estimation-localization-SLAM` without spaces and first first letter small

**Review by akshaykulkarni07 — APPROVED** [review]

**Review by patilunmesh — APPROVED** [review]
I have added some more resources. The rest is fine with me.

**Comment by akshaykulkarni07** [comment]
Since no one (alumni) has objected to any of the content since the past 2 days, I'm merging this PR. Any more changes can be made in new PRs @patilunmesh @Aniket-Gujarathi

**Pull request merged**
