### PR TITLE
Feature/conference

### PR DESCRIPTION
**Pull request by rohant4255**
Add talks, seminars, podcasts, etc.

### CODE REVIEW

**Comment by akshaykulkarni07** [comment]
Can we add Computer Vision and Machine Learning conferences? 
My suggestions:
(listed according to rating on Google Scholar)
Conferences:
IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR) - highest-rated conference among all engineering disciplines
Neural Information Processing Systems (NeurIPS) - for theoretical research in Machine Learning and Computational Neuroscience
International Conference on Learning Representations (ICLR) - for theoretical research in Deep Learning and Representation Learning
European Conference on Computer Vision (ECCV) (even year) / IEEE/CVF International Conference on Computer Vision (ICCV) (odd year) - for theoretical as well as application-based research in Computer Vision and Pattern Recognition
International Conference on Machine Learning (ICML) - for theoretical research in Machine Learning
British Machine Vision Conference (BMVC) - for theoretical as well as application-based research in Computer Vision
Workshop on Applications of Computer Vision (WACV) - more focused towards applications in Computer Vision

**Comment by rohant4255** [comment]
@akshaykvnit Can you please give a brief description for each?

**Comment by akshaykulkarni07** [comment]
I have updated the previous comment, however, I don't know much about the journals.
@SharathRaparthy Please check out the changes made and see if you can add/correct some information.

**Comment by SharathRaparthy** [comment]
@akshaykvnit can we separate cv from ml conferences?

**Comment by akshaykulkarni07** [comment]
> @akshaykvnit can we separate cv from ml conferences?

@SharathRaparthy yes, we can create separate sections for robotics, CV, ML, RL, etc. @rohant4255 if this is okay, I'll make those edits.

**Comment by SharathRaparthy** [comment]
Include the following conferences as well. 
1. Conference on Robot Learning:  This conference focusses on learning-based methods for robots. 
2. Conference on learning theory (CoLT): Pure theoretical machine learning conference 
3. Reinforcement Learning and Decision Making (RLDM): This is the only conference dedicated to pure RL. 
4. AAAI Conference: Covers wide variety of topics in AI. 
5. AAMAS: Famous conference for multi-agent systems
6. AISTATS: Theoretical conference for statistics and machine learning

**Comment by rohant4255** [comment]
Sure, this sounds good to me.

**Comment by rohant4255** [comment]
Also, please make sure you follow the format:
**Full Conference Name (Acronym)**: Description

**Comment by akshaykulkarni07** [comment]
@SharathRaparthy Just check if everything's fine.

**Comment by SharathRaparthy** [comment]
@akshaykvnit this looks good. In journals, just add Journal of Machine Learning (JMLR)

**Comment by akshaykulkarni07** [comment]
Can you add it? You can edit the file actually. Also ICML papers are published in JMLR (so maybe mention that).

**Comment by SharathRaparthy** [comment]
Sure. Makes sense. Go ahead and merge. I'll add later once I am free

**Pull request merged**
