### PR TITLE
Added NLP Course and Review

### PR DESCRIPTION
**Pull request by aayush-fadia**

### CODE REVIEW

**Comment by take2rohit** [comment]
I think natural language processing should have a different README
@GlazeDonuts also has written about it on discord. Please merge both content and modify the PR

**Comment by aayush-fadia** [comment]
So, NLP should be a top level directory like Reinforcement Learning, right?

**Comment by take2rohit** [comment]
Yes @aayush-fadia

**Comment by take2rohit** [comment]
@aayush-fadia @RajGhugare19 @aditya-shirwatkar @GlazeDonuts @rishika2110

Pls resolve this

**Comment by rishika2110** [comment]
Delete this PR, I have created a new readme for NLP. Will open a PR in a few minutes.

**Pull request closed without merging**
