### PR TITLE
added basic RL resources

### PR DESCRIPTION
**Pull request by khush3**
following things can be added: 
Spinning up documentation
More blogs, blogs for different algorithms.

### CODE REVIEW

**Comment by SharathRaparthy** [comment]
Can we add more clean implementations of rl algos? @khush3

**Comment by SharathRaparthy** [comment]
We can also include state of the art papers I guess

**Comment by khush3** [comment]
> Can we add more clean implementations of rl algos? @khush3

I think higgsfield's implementations are sufficient for time-being. We can add things later if we feel.

**Comment by khush3** [comment]
I have added the algorithm based papers. Besides this, I think we should also include papers like HER, GAE, etc

**Comment by take2rohit** [comment]
@SharathRaparthy when you feel that notes are completed please merge it and close this PR

**Comment by SharathRaparthy** [comment]
It's good for now. But definitely will keep on updating this every now and then @take2rohit

**Pull request merged**
